---
namespace: "tcharl"
name: "orchestration_csi"
version: "1.0.1"
description: "Installs and configures a container storage interface"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/orchestration_csi"
documentation: "https://github.com/OsgiliathEnterprise/orchestration_csi/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/orchestration_csi"
issues: "https://github.com/OsgiliathEnterprise/orchestration_csi/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "kubernetes"
  - "hostpath"
  - "cloud"
