---

- name: Csi-volume | install csi namespace
  ansible.builtin.include_role:
    name: tcharl.ansible_orchestration_cli
  vars:
    standalone_role: False
    skip_master_check: Yes
    helm_install: False
    descriptor_sets: # https://github.com/cert-manager/cert-manager/releases/tag/v1.12.1
      - url: https://github.com/kubevirt/hostpath-provisioner-operator.git
        kind: git
        branch: "{{ hostpath_provisioner_operator_version }}"
        descriptors:
          - path: deploy/namespace.yaml
            namespace: hostpath-provisioner

- name: Csi-volume | install webhook
  kubernetes.core.k8s:
    state: present
    src: "{{ hostpath_webhook_url }}"
    ca_cert: "{{ kube_cacert_path | default(omit) }}"
    client_cert: "{{ kube_sysadmin_client_cert_path | default(omit) }}"
    client_key: "{{ kube_sysadmin_client_key_path | default(omit) }}"
    kubeconfig: "{{ kube_config_path }}"
    context: "{{ kube_context | default('kubernetes-admin@kubernetes') }}"
  become: true

- name: Csi-volume | install csi driver
  ansible.builtin.include_role:
    name: tcharl.ansible_orchestration_cli
  vars:
    standalone_role: False
    skip_master_check: Yes
    helm_install: False
    descriptor_sets: # https://github.com/cert-manager/cert-manager/releases/tag/v1.12.1
      - url: https://github.com/kubevirt/hostpath-provisioner-operator.git
        kind: git
        branch: "{{ hostpath_provisioner_operator_version }}"
        descriptors:
          - path: deploy/operator.yaml
            namespace: hostpath-provisioner
          - path: deploy/storageclass-immediate.yaml
            namespace: hostpath-provisioner
          - path: deploy/storageclass-wffc-csi.yaml
            namespace: hostpath-provisioner
          #- path: deploy/storageclass-wffc.yaml
          #  namespace: hostpath-provisioner
- name: Csi-volume | create temp directory to host template
  changed_when: false
  ansible.builtin.tempfile:
    state: directory
    suffix: csi
  register: csi_provisionner_temp_directory

- name: Csi-volume | deduce host path
  ansible.builtin.debug:
    msg: "{{ nfs_mountpoints | default([]) | map(attribute='mountpoints') | flatten | selectattr('csi_mount', 'defined') | selectattr('csi_mount', 'equalto', true) | map(attribute='local') | first }}"
  register: csi_provisionner_host_path

- name: Csi-volume | create csi provisionner configuration
  ansible.builtin.template:
    src: hostpath-csi.yml.j2
    dest: "{{ csi_provisionner_temp_directory.path }}/hostpath-csi.yml"
    mode: '0600'

- name: Csi-volume | execute kubectl apply
  kubernetes.core.k8s:
    state: present
    src: "{{ csi_provisionner_temp_directory.path }}/hostpath-csi.yml"
    ca_cert: "{{ kube_cacert_path | default(omit) }}"
    client_cert: "{{ kube_sysadmin_client_cert_path | default(omit) }}"
    client_key: "{{ kube_sysadmin_client_key_path | default(omit) }}"
    kubeconfig: "{{ kube_config_path }}"
    context: "{{ kube_context | default('kubernetes-admin@kubernetes') }}"
  become: true
