---
- name: Converge master
  hosts:
   - all
  vars:
    secure_logs: False
    # preferred_nic: "eth1"
    kube_firewall_zone: 'public'
    preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    reset_kube: True
    standalone_role: False
    nfs_mountpoints: # Mountpoints should be configured by the tcharl.ansible_volume (nfs mounts) on the server and client side to be mounted on each node before kubernetes comes in
      - host: master.osgiliath.test
        mountpoints:
          - remote: /var/nfs
            csi_mount: Yes
            insecure: True

  roles:
    - role: tcharl.orchestration_csi
