---
- name: Prepare
  hosts:
    - all
  tasks:
    - include_role:
        name: tcharl.orchestration_csi
        tasks_from: requirements.yml
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        idm_preferred_nic: "eth1"
        master_preferred_nic: "eth1"
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
        standalone_role: True
- name: Nfs server
  hosts: master.osgiliath.test
  roles:
    - role: tcharl.nfs_server
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    master_preferred_nic: "eth1"
    company_domain: osgiliath.test
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    standalone_role: True
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
        lvmetanames:
          - lvname: nfs_exposed
            size: 4M
            create: true
            filesystem: xfs
            expose_nfs: True
            mntp: /var/nfs
            mount: true
    manage_lvm: true
    configure_nfs: True
