---
- name: Converge master
  hosts: master.osgiliath.test
  vars:
    kube_firewall_zone: 'public'
    standalone_role: False
    reset_kube: True
#    preferred_nic: "eth1"
    nfs_mountpoints: # Mountpoints should be configured by the tcharl.ansible_volume (nfs mounts) on the server and client side to be mounted on each node before kubernetes comes in
      - host: master.osgiliath.test
        mountpoints:
          - remote: /var/shared/csi
            local: /net
            csi_mount: Yes
#        kube_alt_names:
#          - "kubeadm.osgiliath.net"
  roles:
    - role: tcharl.orchestration_csi
